name: Unit Testing

on:
  push:
    # Avoid using all the resources/limits available by checking only
    # relevant branches and tags. Other branches can be checked via PRs.
    branches: [main]
    tags: ['v[0-9]*', '[0-9]+.[0-9]+*']  # Match tags that resemble a version
  pull_request:  # Run in every PR
  workflow_dispatch:  # Allow manually triggering the workflow
  # schedule:
  #   # Run roughly every 15 days at 00:00 UTC
  #   # (useful to check if updates on dependencies break the package)
  #   - cron: '0 0 1,16 * *'

jobs:
  unit_testing:
    uses: RxnRover/.github/.github/workflows/python_unit_testing_tox_main.yml@main
